title: CompaqDisc's Website
email: bwolbeck@compaqdisc.com
author: Bradan J. Wolbeck (CompaqDisc)
description: >-
  reticulating splines since 2017
baseurl: "/"
url: "https://www.compaqdisc.com"

socials:
  instagram:
    uri: "https://instagram.com/compaqdisc"
  github:
    uri: "https://github.com/CompaqDisc"
  mastodon:
    uri: "https://theomega.zone/@compaqdisc"

donations:
  ko-fi:
    uri: "https://ko-fi.com/compaqdisc"
  nano:
    uri: "nano:nano_1discram3s5yfuenkfacgha6d5e9k3psycm7mf7s4dftpoiy1j696imbi1i8"
  

include: ['~compaqdisc']

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /project/:name/
