title: CompaqDisc's Website
email: bwolbeck@compaqdisc.com
author: Bradan J. Wolbeck (CompaqDisc)
description: >- # ignore newlines
  reticulating splines since 2017
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.compaqdisc.com" # the base hostname & protocol for your site
twitter_username: CompaqDisc
instagram_username: compaqdisc
github_username:  CompaqDisc
nano_address: "nano:nano_1discram3s5yfuenkfacgha6d5e9k3psycm7mf7s4dftpoiy1j696imbi1i8"
#google_analytics: UA-109309717-1

include: ['~compaqdisc']

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /project/:name/
#  auctions:
#    output: true
#    permalink: /emc/:collection/:name/
